version = 0.1
[default.deploy.parameters]
stack_name = "python-scraping-app"
resolve_s3 = true
s3_prefix = "python-scraping-app"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
