AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample Step Functions Scraping Lambda stack (SAM)

Globals:
  Function:
    Timeout: 60
    Runtime: python3.11
    MemorySize: 256

Resources:
  SearchWordReceiverFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: search_word_receiver
      Handler: search_word_receiver.lambda_handler
      CodeUri: src/lambda/
      Policies: AWSLambdaBasicExecutionRole

  GoogleSearchApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: google_search_api
      Handler: google_search_api.lambda_handler
      CodeUri: src/lambda/
      Policies: AWSLambdaBasicExecutionRole

  GoogleDriveUploaderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: google_drive_uploader
      Handler: google_drive_uploader.lambda_handler
      CodeUri: src/lambda/
      Policies: AWSLambdaBasicExecutionRole

  WebScraperFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: web_scraper
      Handler: web_scraper.lambda_handler
      CodeUri: src/lambda/
      Policies: AWSLambdaBasicExecutionRole

  DataProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: data_processor
      Handler: data_processor.lambda_handler
      CodeUri: src/lambda/
      Policies: AWSLambdaBasicExecutionRole

  ResultsHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: results_handler
      Handler: results_handler.lambda_handler
      CodeUri: src/lambda/
      Policies: AWSLambdaBasicExecutionRole

  SheetsUrlRecorderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sheets_url_recorder
      Handler: sheets_url_recorder.lambda_handler
      CodeUri: src/lambda/
      Policies: AWSLambdaBasicExecutionRole

  PageCaptureFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: page_capture
      Handler: page_capture.lambda_handler
      CodeUri: src/lambda/
      Policies: AWSLambdaBasicExecutionRole

  ScrapingStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: scraping-state-machine
      Definition:
        StartAt: SearchWordReceiver
        States:
          SearchWordReceiver:
            Type: Task
            Resource: !GetAtt SearchWordReceiverFunction.Arn
            Next: GoogleSearchApi
          GoogleSearchApi:
            Type: Task
            Resource: !GetAtt GoogleSearchApiFunction.Arn
            Next: MapOverResults
          MapOverResults:
            Type: Map
            ItemsPath: $.searchResults  # GoogleSearchApiの出力配列パスに合わせて調整
            MaxConcurrency: 2
            Iterator:
              StartAt: PageCapture
              States:
                PageCapture:
                  Type: Task
                  Resource: !GetAtt PageCaptureFunction.Arn
                  Next: GoogleDriveUploader
                GoogleDriveUploader:
                  Type: Task
                  Resource: !GetAtt GoogleDriveUploaderFunction.Arn
                  Next: SheetsUrlRecorder
                SheetsUrlRecorder:
                  Type: Task
                  Resource: !GetAtt SheetsUrlRecorderFunction.Arn
                  End: true
            End: true
      RoleArn: !GetAtt StepFunctionsExecutionRole.Arn

  StepFunctionsExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StepFunctionsInvokeLambda
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: "*"
