name: Deploy SAM Application

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli
      - name: SAM build
        run: sam build
      - name: SAM deploy
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name step-functions-scraping --capabilities CAPABILITY_IAM --region ap-northeast-1
