name: Deploy Lambda

on:
  workflow_dispatch:
    inputs:
      lambda_function_name:
        description: 'Lambda function name'
        required: true
        default: 'your-lambda-function-name'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Zip Lambda source
        run: |
          cd src/lambda
          zip -r ../lambda_function.zip .
          cd ../..
      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{ github.event.inputs.lambda_function_name }} \
            --zip-file fileb://src/lambda_function.zip
      - name: Clean up
        run: rm src/lambda_function.zip
